### ISSUE TITLE
setup folder missing

### ISSUE THREAD

**Issue by pAt84** [plainmade/unmark#103]
Hi,

ok, the readme.md says to run  "your-unmark-url/setup" but either I am blind or something is wrong because there is no setup folder in the repository?

Best
P

**Comment by williamknauss** [comment]
Hi @pAt84,
Unmark is built on a PHP framework called CodeIgniter which has some pretty cool routing built in. When you access your-unmark-url/setup, CodeIgniter (via url rewrites) actually sees http://your-unmark-url/index.php/setup. The basics is that CodeIgniter will try to locate a file (called a controller) in ./application/controllers and execute the default "index" method.

You can read all about CodeIgniters cool jazz [here.] (http://www.codeigniter.com/user_guide/)

Cheers Mate

**Comment by pAt84** [comment]
Hi,

thanks for the guidelines, did not know about codegniter. I actually had to explicitely add the "index.php" in the URL. Unfortunately it does not work this way either. If I click "install" it gives me "Not Found / The requested URL /install was not found on this server.". I also added "DirectoryIndex index.php" in the apache config to Directory which hosts my entire webpage, including unmark but it does not help.

Cheers for your initial answer. Hope you could lend me a hand again.

Best
P

**Comment by williamknauss** [comment]
Hi @pAt84,
At this point Unmark requires that URL rewrites are enabled. (As a side note Unmark has to be installed in the root of your subdomain not a subdirectory). Try setting your Directory directive to something like this:

```
<Directory "path/to/Unmark">
        RewriteEngine On
        Options FollowSymLinks Indexes
        AllowOverride AuthConfig Options FileInfo
    </Directory>
```

**Comment by pAt84** [comment]
Hi,

thanks for the quick response again William. I really appreciate it. Unfortunately the error message remains. It is installed in the root. The apache config has this statement in now:

DocumentRoot /var/www/
        <Directory />
                RewriteEngine On
                Options FollowSymLinks Indexes
                AllowOverride AuthConfig Options FileInfo
        </Directory>

Also adding a <Directory /unmark> will not do the trick. 

The apache error log shows no errors. 

:/

Best
Pat

**Comment by williamknauss** [comment]
Try setting your virtual host to this, also keep in mind that apache mod_rewrite needs to be enabled.

```
<VirtualHost *:80>
    ServerName yourunmarkurl.com
    DocumentRoot "/var/www"
   <Directory "/var/www">
        RewriteEngine On
        Options FollowSymLinks Indexes
        AllowOverride All
    </Directory>
</VirtualHost>
```

**Comment by pAt84** [comment]
No, no luck. You previously wrote that unmark should be installed in the root. Did you mean / or can I have www.mydomain.com/unmark because I went for the second option. I could go with the first option if I add a subdomain.

**Comment by pAt84** [comment]
Ok yeah, moving it to a subdomain (i.e. unmark.mydomain.com) did the trick. :)

**Comment by karibuTW** [comment]
Hi guys,

Great software! I've made an article on my blog to explain how to install it for those having difficulties (With a subdomain, it works great indeed)

Here is the link if needed:
http://freedif.org/unmark-the-to-do-list-for-your-bookmarks/

Keep the good work up!

**Comment by cdevroe** [comment]
@karibuTW Thanks for the write-up.

**Comment by williamknauss** [comment]
Hi @karibuTW,
Thanks for the awesome writeup mate!

**Comment by dp87** [comment]
Unfortunately I am having the same issue. I think all the prerequisites are there:

* mod_rewrite is enabled
* php is version 5.5.24
* mysql is version 5.5.x
* I have created a virtual host for unmark
* The database table and user have been created (the user has permissions to do everything on the unmark table)
* database.php contains the correct credentials

I have also followed @karibuTW 's tutorial but I get the same error when I try to open the setup page. I know that unmark at the moment does not support subdirectories, but following the guide mentioned above it seems that this can be made to work using subdomains (i.e. my subdomain is unmark.webserver and the document root is /var/www/unmark).

Can you absolutely confirm that this setup is still unsupported?
