### ISSUE TITLE
Grunt, Grunt, Oink, Oink

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#109]
Hello,
"DISCLAIMER": I have never used Grunt before this weekend. So please consider me a novice.

So this weekend I was working on rebuilding some of the javascript urls, so I followed the instructions to setup Grunt. I kept running the command "grunt" and was presented with an error 
```
Running "sass:prod" (sass) task

Running "uglify:prod" (uglify) task
File "assets/js/production/unmark.plugins.js" created
Warning: Cannot assign to read only property 'subarray of var Hogan={};....
```

Using my favorite search engine (Google) I found countless results of similar errors (behavior) using Grunt and Uglify. After trying a few suggestions mentioned on other sites to no avail I gave up. Then I woke up this morning with some inspiration. I updated the version of uglify in package.json to version 0.8.0 and ran 'npm install'. Once NPM said everything was good to go I ran 'grunt' and to my suprise there were no errors! WOOT WOOT! :gift:

**Comment by cdevroe** [comment]
This makes sense. I say update.
