### ISSUE TITLE
Expired Certificate error

### ISSUE THREAD

**Issue by impressivewebs** [plainmade/unmark#117]
The website is pushing out an expired security certificate error, claiming it's unsafe to visit. Says the certificate expired 7 days ago.

**Comment by williamknauss** [comment]
@cdevroe,
You might want to take a look at this.

**Comment by cdevroe** [comment]
@impressivewebs @williamknauss Yes! Thank you. We purchased it. But our ops person has been unresponsive for a few weeks. We're looking for a new one.

Anyone volunteering? Need an Nginx expert.

**Comment by williamknauss** [comment]
@cdevroe do you need an Nginx expert or just someone to install your new cert?

**Comment by cdevroe** [comment]
@williamknauss It is installed!

**Comment by williamknauss** [comment]
Woot Woot! Yeah for 1 more year! :sparkling_heart: :heart_eyes_cat:
