### ISSUE TITLE
auto completion on hashtag #feature request

### ISSUE THREAD

**Issue by tboulogne** [plainmade/unmark#119]
Hello,

Great job on unmark !
An interesting feature could be to have autocompletion on hashtag to avoid duplicates (#data and #datas...)

Thanks :-).

Thierry

**Comment by ckrack** [comment]
+1
this should be in the notes and in the chrome extension.
if possible also in the bookmarklet.

**Comment by cdevroe** [comment]
@tboulogne Thanks for the suggestion. As @ckrack said this is a dupe. So we are going to do it!

**Comment by tboulogne** [comment]
thanks :-)
