### ISSUE TITLE
Is there an API for unmark?

### ISSUE THREAD

**Issue by PaBLoX-CL** [plainmade/unmark#120]
Hi!

Just found unmark, and I was wondering if an API exists (I didn't find anything in the wiki nor the website). If not, it's in some sort of roadmap?

Sorry if this has been already discussed, or posted somewhere else ._.

**Comment by PaBLoX-CL** [comment]
LOL, just **after** posting the issue I found:

https://github.com/plainmade/unmark/wiki/Response-Logic

> The application is pretty much self aware of the response type to send you based on the request. There is no need to call a different url for the API vs. web view vs. internal XMLHttpRequest call. They are all the same.

Anyway, a link in the FAQ or in the footer could redirect to that wiki page :).

**Comment by cdevroe** [comment]
@PaBLoX-CL That's @phpfunk being awesome again.

That said... this is an internal API and not a public one with API keys and all of that. Just so you're clear. I still think we should add an API to Unmark for data transactions beyond the application itself at some point. Especially for http://unmark.it

**Comment by PaBLoX-CL** [comment]
Ohh... ok, now I understand. I was wondering for a public one. And yes, you should add one ^_^U

**Comment by nitinthewiz** [comment]
Just out of curiosity, is the Response Logic based API because of CodeIgniter features or is it something you built into Unmark? I tried looking for such logic in Code Igniter's docs but perhaps you're using some extension I'm not aware of...

**Comment by phpfunk** [comment]
@nitinthewiz no the response logic is not built into CI. It's very easy to implement though. Have a base controller figure out if it's an XMLHttpRequest, incoming API call or internal request and respond with the data accordingly. If you were using Angular for example it would be super easy, just return everything as JSON and call it a day.

All that data stays the same except in this case we return one as an array and others as JSON.

This method figures out what to return: https://github.com/plainmade/unmark/blob/master/application/core/Plain_Controller.php#L269

**Comment by jamesacampbell** [comment]
Im looking for a way to use the API to generate a summary of tagged bookmarks for the week that I can generate and email from and send to my team as a 'suggested reads' list. I already do this with Pinboard, but trying to port everything over to unmark and get rid of my last non-self-hosted service. Any help would be much appreciated. Cheers.
