### ISSUE TITLE
Install problem : blank page

### ISSUE THREAD

**Issue by FromBabylon** [plainmade/unmark#121]
Hi,

I'm having some troubles to reach setup screen with nginx. It used to work very well with the exact same config. (the one from the wiki with one or two small changes)

If I put a test.php file in unmark folder I can reach it so both nginx and php-fpm seems well configured. However every other request ends up with a blank page. No errors in any logs

I have this problem on Archlinux and have just tried in a LXC ubuntu container but same issue.

Any idea ?

Update : if I make a wrong request on purpose such as https://domain.com/fmQHKFQF then I'll see unmark 404 error page (the one with a big red cross)

**Comment by williamknauss** [comment]
Hi @FromBabylon,
Sorry you are having issues getting Unmark installed. I know one of the more frequent reasons for getting a white page with no errors is because the PHP gettext extension isn't installed or enabled. I would suggest checking that and letting us know.

Thanks

**Comment by FromBabylon** [comment]
Hi,

Unfortunately php extension gettext is enabled. Which other extensions are required for unmark to work properly ?

**Comment by Pacien** [comment]
Hi,

I had a similar issue using the configuration file provided on the Wiki.
I obtained blank pages with a 200 status code on `/`, `/setup` or any `.php` file put in the root.

I solved this by adding the following line to the virtual host configuration file in the `location ~ \.php$` section:
>         fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;

**Comment by FromBabylon** [comment]
@Pacien  Thanks for your suggestion however I already use the config from the wiki with the directive for SCRIPT_FILENAME. I tried `$document_root/$fastcgi_script_name;` `$document_root$fastcgi_script_name;` and even by importing fastcgi.conf (which do the same job..)

**Comment by cdevroe** [comment]
@FromBabylon Were you ever able to solve this issue? Any other nginx peeps have feedback?

**Comment by cdevroe** [comment]
I'm going to close this ticket as it has been six months.
