### ISSUE TITLE
chrome-extension: adding note requires two clicks

### ISSUE THREAD

**Issue by ckrack** [plainmade/unmark#124]
When adding a note or tags to a new mark in the chrome extension, two clicks are required.
After the first click on "ADD NOTE", a second click on "Type note text here" is necessary.
This should be one. 
I suggest changing the label to: "Add note by typing text here".

**Comment by cdevroe** [comment]
@ckrack Good suggestion. Want to add that and submit a PR? https://github.com/plainmade/unmark-chrome
