### ISSUE TITLE
Where to add metatags ?

### ISSUE THREAD

**Issue by bitsandnumbers** [plainmade/unmark#125]
I'd like to add a metatag to get Unmark in fullscreen when opening from a homescreen iPad bookmark. Where should I put it? I see a lot of php files but have no idea how to add this specific metatag inside such files. 

Here's the meta in question:  
 <meta name="apple-mobile-web-app-capable" content="yes">

**Comment by cdevroe** [comment]
@bitsandnumbers If you're asking how to add to the HTML... that file is: /application/views/layouts/header.php
