### ISSUE TITLE
/setup not found

### ISSUE THREAD

**Issue by cjrobe** [plainmade/unmark#127]
I'm stuck at the installation step where you point your browser to unmark/setup. There's no file or folder named setup in the zip I downloaded and when I try and load the URL, I get a 404. Any pointers? Does this mean that my server doesn't support URL rewrites?

**Comment by psybermancer** [comment]
I'm having exactly the same issue.

**Comment by lajlev** [comment]
Make sure to transfer the `.gitignore`and `.htaccess` file to server

**Comment by trotzendorff** [comment]
Yay! Thanks a lot your your solution! Blame it on the heat in Germany. ;-)

**Comment by cdevroe** [comment]
@trotzendorff @cjrobe Can this be closed?

**Comment by trotzendorff** [comment]
Fine for me. Thanks!

**Comment by cjrobe** [comment]
I have both .gitignore and .htaccess on my FTP but still no luck.

It says "The requested URL /index.php was not found on this server."

Here's the URL if it helps.
http://cory-r.com/bmarx/setup

**Comment by trotzendorff** [comment]
Ok, that's not a problem of those files. »At this point Unmark has to be installed on the root of your subdomain. Installation of Unmark in a sub directory is unsupported at this time. Keep tabs on our progress with this issue by monitoring this issue.« So if you try to again install it in the root of http://cory-r.com/, everything should be fine.

**Comment by cjrobe** [comment]
Thanks for the response. I just noticed that when I loaded http://cory-r.com/bmarx/ and the image 404'd.

I'm in the process of creating a subdomain bmarx.cory-r.com. That should solve the issue, correct?

**Comment by trotzendorff** [comment]
Correct. I also installed Unmark in a subdomain and it works perfectly.
