### ISSUE TITLE
Does search only search page titles, or content as well? [Feature Request]

### ISSUE THREAD

**Issue by ajohnson23** [plainmade/unmark#133]
Hello,

Does the search feature within Unmark support searching page content, or just page titles?

Thanks.

**Comment by cdevroe** [comment]
@ajohnson23 It doesn't cache much page content locally -- just title, url, oembed, and your notes. So while it doesn't search page content it does search your notes field.

**Comment by ajohnson23** [comment]
I just have to say (in my opinion), this limits the usefulness of unmark quite significantly. If page content isn't cached and searched, that means I have to be very thorough in my tag/naming choices, which is practically impossible, so I'll end up not being able to find a bookmark later because I can't think of the "correct" search term to use to find it.

I'd like to convert this into a feature request. Someday I hope unmark will support this!

**Comment by cdevroe** [comment]
@ajohnson23 This creates a fair amount of complexity in the application. Perhaps Pinboard's Archiving account, which I believe caches a copy of the site, may be of better use to you? https://pinboard.in/upgrade/

**Comment by ajohnson23** [comment]
Hi cdevroe:

You're the first company I've seen in this space that adopts a sensible attitude regarding open source and self hosting vs. what's out there, including pinboard.

Currently the following services offer something similar, but have no open source / self-hosted solution, so I refuse to pay for them since my data and the functionality is held hostage on their servers and goes poof if they get acquired/shut down:
https://pinboard.in/
http://historio.us/
http://fetching.io/
https://www.kifi.com/

If you added this feature and I knew I could one day get my data out of it and run it on my own server if you got acquired / shut down / went poof,  pay more than $12 per year for it until that happened.

**Comment by ajohnson23** [comment]
Don't get me wrong, though -- I know this adds a fair bit of complexity. I just happen to think it's worth it.

**Comment by ajohnson23** [comment]
I'm also trying to convince some of those companies on my list to adopt a more sensible attitude toward self-hosting/open source, but I'm not holding my breath on that -- I actually think there's a better chance of you adding this functionality, so that's why I've opened this ticket :)

**Comment by cdevroe** [comment]
Only marking this as invalid as we're not going to be adding full page text search. We really want to stick to our "mantra" of "the to do app for bookmarks". If people would like a more robust archiving system we wholeheartedly recommend Pinboard.
