### ISSUE TITLE
Feature request: add new users

### ISSUE THREAD

**Issue by drupallerina** [plainmade/unmark#134]
Hello,

First, unmark is really cool. I've been looking for a good application for my bookmarks for a long time and unmark seems to fit!
I just installed it on my server and immediately wanted to give access to my family but I can only find the option to invite people to unmark.it
It would be awesome if I could invite people to my unmark it installation.

**Comment by cdevroe** [comment]
@drupallerina The installable version of Unmark is more tailored to a single-user experience. However, you can edit this file to point towards your install URL https://github.com/plainmade/unmark/blob/master/application/views/layouts/accountlinks.php

**Comment by cdevroe** [comment]
We're going to close this out as we won't be adding multi-user support to Unmark in the near future.
