### ISSUE TITLE
HTTP 500 on /setup

### ISSUE THREAD

**Issue by baratox** [plainmade/unmark#137]
I'm unable to setup Unmark with Ubuntu 14.04, Apache 2.4.7, PHP 5.5.9-1ubuntu4.14 and MySQL 5.5.46.

/setup returns HTTP 500, a blank page and no log (apache, php or application/logs).
Any help on how i can troubleshoot this?

Site seems to be configured and executing, i see unmark's 404 page when trying to access an invalid URL. 

Thanks!

**Comment by baratox** [comment]
Setting `$config['log_threshould'] = 4` in *application/config/config.php* adds just a few lines to the application log when accessing */setup*, but nothing on the error:

    DEBUG - 2015-12-13 18:57:04 --> Config Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Plain_Config Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Hooks Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Plain_Hooks Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Utf8 Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> UTF-8 Support Enabled
    DEBUG - 2015-12-13 18:57:04 --> URI Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Router Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Plain_Router Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Output Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Security Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Input Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Global POST and COOKIE data sanitized
    DEBUG - 2015-12-13 18:57:04 --> Language Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Loader Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Plain_Loader Class Initialized
    DEBUG - 2015-12-13 18:57:04 --> Config file loaded: application/config/all/app.php
    DEBUG - 2015-12-13 18:57:04 --> Helper loaded: data_helper
    DEBUG - 2015-12-13 18:57:04 --> Helper loaded: hash_helper
    DEBUG - 2015-12-13 18:57:04 --> Helper loaded: validation_helper
    DEBUG - 2015-12-13 18:57:04 --> Helper loaded: view_helper
    DEBUG - 2015-12-13 18:57:04 --> Helper loaded: url_helper
    DEBUG - 2015-12-13 18:57:04 --> Database Driver Class Initialized

**Comment by cherepo** [comment]
Same thing here, downloaded the latest release package and setup got blank page.

**Comment by cdevroe** [comment]
@baratox The log file should contain an error if there is one at the PHP level. A few common things that others have missed;

- Unmark requires gettext extension to be compiled and loaded with PHP. This has resulted in a "blank page" for some -- though in those instances the log file shows that bindtextdomain() is not defined.
- The last thing to load in your error log appears to be the Database class. Can you verify that you have the proper database credentials in your /applications/config/database.php file? (you'll have to create this file yourself)
- Anything else "out of the ordinary" with your stack?

**Comment by baratox** [comment]
@cdevroe I've managed to identify problem with the permissions of the database user by creating a custom PHP database client. 

If there is a configuration error, the logs do not provide any help, only "Database Driver Class Initialized" is logged. It can be useful to print the database error code or message when a DB command fails. I've seen some exception handling in the code but this did not help with the initial setup.

**Comment by Larnal** [comment]
@baratox Hi, I got the same problem you had, unfortunately I am not very experienced in debugging nor developping, can you explain the procedure you used to fix this issue ?

I am on OSMC (modified Raspbian on Rpi2) with PHP 5.6.17, Nginx 1.6.2 and MySQL 5.5.47.

Thank you very much.

**Comment by cdevroe** [comment]
@baratox @Larnal Please try #157 to see if this cleans up your issues. It should.
