### ISSUE TITLE
Setting SQLite fails to load page

### ISSUE THREAD

**Issue by maxsteenbergen** [plainmade/unmark#14]
There seems to be an issue with SQLite support. I tried installing with SQLite because I didn't feel like installing MySQL and SQLite comes with OSX, yet I failed to get even an error screen. 

Setting `$db['default']['dbdriver'] = 'mysql';` on line 65 of database.php shows this screen: 
![screen shot 2014-01-07 at 20 20 03](https://f.cloud.github.com/assets/574278/1862403/dd53f3c6-77d0-11e3-871c-44a652ec5b6a.png)

`$db['default']['dbdriver'] = 'sqlite';` shows this blank page:
![screen shot 2014-01-07 at 20 20 48](https://f.cloud.github.com/assets/574278/1862406/f0896db8-77d0-11e3-9ede-7a16b0599294.png)

Is this my bad?

**Comment by mbirth** [comment]
Same issue here. Tried to install with SQLite3, but it fails applying the files from the `migrations` directory since all the queries are written in MySQL (e.g. `AUTO_INCREMENT` instead of `AUTOINCREMENT`).
