### ISSUE TITLE
Feature: Edit/delete tags

### ISSUE THREAD

**Issue by ckrack** [plainmade/unmark#141]
Editing tags should change them in the tags table in the database, but also in the comment field.

**Comment by cdevroe** [comment]
@ckrack Can you explain further what you'd like to happen here? Where do you see "editing tags" happening? Is this mostly to help correct misspellings and the like?

**Comment by cdevroe** [comment]
@ckrack I'm going to close this because we're preparing to switch Unmark to a more traditional tagging model that has a dedicated spot in the UI for "tags" which would result in what you're saying with updating the index.

(Hope that made sense.)
