### ISSUE TITLE
Blank page on setup

### ISSUE THREAD

**Issue by mfpost** [plainmade/unmark#143]
I am trying to get unmark to run on my DigitalOcean droplet.  I am running ubuntu 15.10.  I have wordpress installed (on www.myDomain.com).  I am using nginx.  I am trying to run unmark at unmark.myDomain.com, but when I go to unmark.myDomain.com/setup I just get a blank page.  I used the non-ssh config from here (https://github.com/plainmade/unmark/wiki/Nginx-Configuration).  I pasted that into the same nginx config I have for wordpress.  Wordpress has a root of /var/www and unmark's root is /var/www/unmark.  I am guessing this is a configuration issue but I don't know what is wrong.

**Comment by nitinthewiz** [comment]
@mfpost could you please post your nginx config? Also, did you paste it into the same config file as your wordpress file? You'd be better off using different files in the sites-available folder as seen below - 

https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-virtual-hosts-server-blocks-on-ubuntu-12-04-lts--3

**Comment by mfpost** [comment]
I'm sorry I haven't been using nginx too long what config file are you wanting, where do I find it?  I have attached the server blocks for wordpress and unmark.  I separated them out like you recommended, but I am still having the same issue.  In fact it made things worse for WP.  Now WP has some of the background colors messed up.  I am guessing it can't find a style sheet or something like that.  But I am not sure how to fix it.  

[unmark.txt](https://github.com/plainmade/unmark/files/92690/unmark.txt)
[wordpress.txt](https://github.com/plainmade/unmark/files/92691/wordpress.txt)

**Comment by nitinthewiz** [comment]
@mfpost look for solutions here - 
http://stackoverflow.com/questions/11693135/multiple-websites-on-nginx-sites-available
and 
https://www.linode.com/docs/websites/nginx/how-to-configure-nginx

This is where these files sit - 
/etc/nginx/sites-available/

Essentially, you make different files for each site which would start off as a copy of the default file and then have syntax specific for each type of site.

Here's some of my WP config - 

	root /var/www;
	index index.php index.html index.htm;
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ /index.php?q=$uri&$args;

		# added based on
		# http://howtounix.info/howto/110-connection-timed-out-error-in-nginx
		# on 11/4/2015 by Nitin Khanna
		# proxy_read_timeout 300;
		
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}
	location ~ \.php$ {
			try_files $uri =404;
			fastcgi_pass unix:/var/run/php5-fpm.sock;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include fastcgi_params;
	}

Currently, the first problem I am seeing is that you need to make sure that PHP5-FPM is setup correctly. For that, look to this excellent tutorial which I've used before to setup my stuff - 

https://www.digitalocean.com/community/tutorials/how-to-host-multiple-websites-securely-with-nginx-and-php-fpm-on-ubuntu-14-04

**Comment by mfpost** [comment]
Thanks for the help.  I finally got it working.  Not really sure what fixed it.  But after I got my wordpress working unmark started working fine.
