### ISSUE TITLE
Update mysql to mysqli in database-sample.php

### ISSUE THREAD

**Issue by flawiddsouza** [plainmade/unmark#146]
According to https://www.codeigniter.com/user_guide/database/configuration.html `mysql` is deprecated and `mysqli` should be used instead. Though, I could be wrong. I had to change mine to `mysqli` to get it to work. `mysql` requires you to use the older `mysql` extension which isn't shipped with PHP anymore.

**Comment by cdevroe** [comment]
@flawiddsouza I'll be sure this gets in an upcoming release.
