### ISSUE TITLE
Export function only leading to a blank page

### ISSUE THREAD

**Issue by quizzmaster** [plainmade/unmark#151]
If i try to export my bookmarks on my self-hosted unmark site i only get a blank page and need to login again. Anything I can check or any solutions to solve this?

**Comment by cdevroe** [comment]
@quizzmaster Can you pull down PR #153 and see if it fixes you're issue please?

**Comment by cdevroe** [comment]
@quizzmaster Were you able to try this? You can also update to 1.7.0 to see.

**Comment by cdevroe** [comment]
@quizzmaster I was able to replicate this issue. Looking into it.

**Comment by cdevroe** [comment]
@quizzmaster I've fixed this issue in #157.
