### ISSUE TITLE
auto tag?

### ISSUE THREAD

**Issue by Hans-Maulwurf** [plainmade/unmark#154]
Hey guys,
i noticed that the label "watch" is pre-chosen when I mark a youtube.vid. Is there a feature how to create such rules? Where can I see the existing rules? Is it possible to create such rules manually? Maybe in some config-files?

**Comment by cdevroe** [comment]
@Hans-Maulwurf Unmark does two things out of the box; 1) it has a few preconfigured "smart labels" where we guess what you'd likely label the link based on the domain. YouTube, Amazon, Vimeo, etc. are just a few that we've added that made sense to us. 2) It remembers the last label you chose for each domain. So when you label something from abccompany.com as "Read" Unmark will choose "read" the next time as well.

One way to extend this list is to look in the "labels" table in the database and see the default smart labels that are already configured. And then extend them based on your own wishes.

**Comment by Hans-Maulwurf** [comment]
Ah ok, I see. Thanks for the explanation. So it's only possible to auto-label the marks by domain, right? Is it possible to do this also by keywords of the title or the (preview-)content?

Is there a function that does the same with tags and not only with the label?
