### ISSUE TITLE
Import from Readability

### ISSUE THREAD

**Issue by cdevroe** [plainmade/unmark#156]
A proposal to import your Readability list.

https://twitter.com/Darice/status/775680361384861696

Can someone give us a dump of their Readability bookmarks? I exported mine but I had none!

**Comment by Darice** [comment]
Here is my Readability export. It's a json file. 

[readabilty-export.json.zip](https://github.com/plainmade/unmark/files/470124/readabilty-export.json.zip)

**Comment by cdevroe** [comment]
@Darice Thanks! I'll get working on this today.

**Comment by cdevroe** [comment]
@Darice You can give #158 a try and see if it works for you.

**Comment by cdevroe** [comment]
@Darice Here is this branch as a zip for you to try. 
[unmark.zip](https://github.com/plainmade/unmark/files/475035/unmark.zip)

**Comment by Darice** [comment]
@cdevroe I updated my hosted install to this branch. Imported my Readability json file. Added a new bookmark in unmark just to make sure everything works. No problems. Works fine for me.

Thanks for adding the readability import option!

**Comment by cdevroe** [comment]
@Darice Excellent!
