### ISSUE TITLE
Issue during setup. mitigation_table variable is not being set.

### ISSUE THREAD

**Issue by nospam1961** [plainmade/unmark#160]
After clicking "INSTALL" link on the new install (database, user, and password was set in database.php). User has all of the privileges in the database. Version Tested: 1.7.0.

> 
> AN ERROR WAS ENCOUNTERED
> 
> Migrations configuration file (migration.php) must have "migration_table" set.
>

**Comment by moltenkaizen** [comment]
Very interested, I have the same error. I've re-setup a few times on different VMs to confirm.

**Comment by nospam1961** [comment]
@cdevroe Just tried #157. Overwriting 9 files from the fix have done the trick. 
Closing issue.
Thank You.
