### ISSUE TITLE
Whites Screen after login

### ISSUE THREAD

**Issue by zu** [plainmade/unmark#164]
Installation seemed to go smoothlie but after I login I only get a white screen.

Now I changed to development environment and I get follwing log:

`DEBUG - 2016-09-21 10:43:30 --> Config Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Plain_Config Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Hooks Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Plain_Hooks Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Utf8 Class Initialized
DEBUG - 2016-09-21 10:43:30 --> UTF-8 Support Enabled
DEBUG - 2016-09-21 10:43:30 --> URI Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Router Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Plain_Router Class Initialized
DEBUG - 2016-09-21 10:43:30 --> No URI present. Default controller set.
DEBUG - 2016-09-21 10:43:30 --> Output Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Security Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Input Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Global POST and COOKIE data sanitized
DEBUG - 2016-09-21 10:43:30 --> Language Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Loader Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Plain_Loader Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Config file loaded: application/config/all/app.php
DEBUG - 2016-09-21 10:43:30 --> Helper loaded: data_helper
DEBUG - 2016-09-21 10:43:30 --> Helper loaded: hash_helper
DEBUG - 2016-09-21 10:43:30 --> Helper loaded: validation_helper
DEBUG - 2016-09-21 10:43:30 --> Helper loaded: view_helper
DEBUG - 2016-09-21 10:43:30 --> Helper loaded: url_helper
DEBUG - 2016-09-21 10:43:30 --> Database Driver Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Controller Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Plain Session Class Initialized
DEBUG - 2016-09-21 10:43:30 --> Helper loaded: string_helper
DEBUG - 2016-09-21 10:43:30 --> Database Driver Class Initialized
DEBUG - 2016-09-21 10:43:30 --> [CIDatabaseSessionHandler] Open called
DEBUG - 2016-09-21 10:43:30 --> [CIDatabaseSessionHandler] Read called
DEBUG - 2016-09-21 10:43:30 --> Session data not found.
DEBUG - 2016-09-21 10:43:30 --> Session routines successfully run
DEBUG - 2016-09-21 10:43:30 --> Config file loaded: application/config/all/language.php
DEBUG - 2016-09-21 10:43:30 --> File loaded: application/views/layouts/footer_unlogged_scripts.php
DEBUG - 2016-09-21 10:43:30 --> File loaded: application/views/welcome.php
DEBUG - 2016-09-21 10:43:30 --> Final output sent to browser
DEBUG - 2016-09-21 10:43:30 --> Total execution time: 0.0319
DEBUG - 2016-09-21 10:43:30 --> [CIDatabaseSessionHandler] Write called
DEBUG - 2016-09-21 10:43:30 --> [CIDatabaseSessionHandler] Read called
DEBUG - 2016-09-21 10:43:30 --> [CIDatabaseSessionHandler] Close called
DEBUG - 2016-09-21 10:43:48 --> Config Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Plain_Config Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Hooks Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Plain_Hooks Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Utf8 Class Initialized
DEBUG - 2016-09-21 10:43:48 --> UTF-8 Support Enabled
DEBUG - 2016-09-21 10:43:48 --> URI Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Router Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Plain_Router Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Output Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Security Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Input Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Global POST and COOKIE data sanitized
DEBUG - 2016-09-21 10:43:48 --> Language Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Loader Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Plain_Loader Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Config file loaded: application/config/all/app.php
DEBUG - 2016-09-21 10:43:48 --> Helper loaded: data_helper
DEBUG - 2016-09-21 10:43:48 --> Helper loaded: hash_helper
DEBUG - 2016-09-21 10:43:48 --> Helper loaded: validation_helper
DEBUG - 2016-09-21 10:43:48 --> Helper loaded: view_helper
DEBUG - 2016-09-21 10:43:48 --> Helper loaded: url_helper
DEBUG - 2016-09-21 10:43:48 --> Database Driver Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Controller Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Plain Session Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Helper loaded: string_helper
DEBUG - 2016-09-21 10:43:48 --> Database Driver Class Initialized
DEBUG - 2016-09-21 10:43:48 --> [CIDatabaseSessionHandler] Open called
DEBUG - 2016-09-21 10:43:48 --> [CIDatabaseSessionHandler] Read called
DEBUG - 2016-09-21 10:43:48 --> Session routines successfully run
DEBUG - 2016-09-21 10:43:48 --> Config file loaded: application/config/all/language.php
DEBUG - 2016-09-21 10:43:48 --> Model Class Initialized
DEBUG - 2016-09-21 10:43:48 --> Model Class Initialized
DEBUG - 2016-09-21 10:43:48 --> File loaded: application/views/json/index.php
DEBUG - 2016-09-21 10:43:48 --> Final output sent to browser
DEBUG - 2016-09-21 10:43:48 --> Total execution time: 0.0583
DEBUG - 2016-09-21 10:43:48 --> [CIDatabaseSessionHandler] Write called
DEBUG - 2016-09-21 10:43:48 --> [CIDatabaseSessionHandler] Read called
DEBUG - 2016-09-21 10:43:48 --> [CIDatabaseSessionHandler] Close called
DEBUG - 2016-09-21 10:43:49 --> Config Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Plain_Config Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Hooks Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Plain_Hooks Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Utf8 Class Initialized
DEBUG - 2016-09-21 10:43:49 --> UTF-8 Support Enabled
DEBUG - 2016-09-21 10:43:49 --> URI Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Router Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Plain_Router Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Output Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Security Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Input Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Global POST and COOKIE data sanitized
DEBUG - 2016-09-21 10:43:49 --> Language Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Loader Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Plain_Loader Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Config file loaded: application/config/all/app.php
DEBUG - 2016-09-21 10:43:49 --> Helper loaded: data_helper
DEBUG - 2016-09-21 10:43:49 --> Helper loaded: hash_helper
DEBUG - 2016-09-21 10:43:49 --> Helper loaded: validation_helper
DEBUG - 2016-09-21 10:43:49 --> Helper loaded: view_helper
DEBUG - 2016-09-21 10:43:49 --> Helper loaded: url_helper
DEBUG - 2016-09-21 10:43:49 --> Database Driver Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Controller Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Plain Session Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Helper loaded: string_helper
DEBUG - 2016-09-21 10:43:49 --> Database Driver Class Initialized
DEBUG - 2016-09-21 10:43:49 --> [CIDatabaseSessionHandler] Open called
DEBUG - 2016-09-21 10:43:49 --> [CIDatabaseSessionHandler] Read called
DEBUG - 2016-09-21 10:43:49 --> Session routines successfully run
DEBUG - 2016-09-21 10:43:49 --> Config file loaded: application/config/all/language.php
DEBUG - 2016-09-21 10:43:49 --> Model Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Model Class Initialized
DEBUG - 2016-09-21 10:43:49 --> Session class already loaded. Second attempt ignored.
ERROR - 2016-09-21 10:43:49 --> Array
(
    [message] => Exception: Call to undefined function unmark_ngettext()
    [type] => Exception
    [backtrace] => /path-to]/unmark/application/helpers/data_helper.php
    [custom_data] => Array
        (
        )

    [enviornment] => development
    [user] => Array
        (
            [user_id] => 1
            [email] => [myemail-address]
            [user_token] => tDMn5bkVAkueLFZ6JJA7JBy0QuruVzfa4abea1560ca1791fed0a56b17234f3
            [active] => 1
            [admin] => 0
            [created_on] => 2016-09-21 10:24:57
            [last_updated] => 2016-09-21 10:24:57
        )

)

DEBUG - 2016-09-21 10:43:49 --> [CIDatabaseSessionHandler] Write called
DEBUG - 2016-09-21 10:43:49 --> [CIDatabaseSessionHandler] Read called
DEBUG - 2016-09-21 10:43:49 --> [CIDatabaseSessionHandler] Close called
`

**Comment by cdevroe** [comment]
@zu Thanks for reporting this. This is a result of a bad merge. Really appreciate it. Going to submit a patch this morning. Waiting for ☕️  to kick in. ;-)

**Comment by cdevroe** [comment]
@zu Can you try 1.7.1.1 https://github.com/plainmade/unmark/releases/tag/v1.7.1.1

**Comment by zu** [comment]
Thanks, it looks much better now!
No problems, it works.
