### ISSUE TITLE
Password reset link not working

### ISSUE THREAD

**Issue by zu** [plainmade/unmark#165]
It looks like the password reset link uses a strange kind of IP6 address instead of the domain and is not working. I was able to replace the ip address with the domain in the url manually and then it worked.

But it's a bit strange.

Original URL (without the unique hash of course) I got by mail:

`http://2a00:1158:400:406::14e/password_reset/...`

Is this a configuration issue or a bug?

**Comment by cdevroe** [comment]
@zu Can you tell me if base_url is set in your configuration?

**Comment by cdevroe** [comment]
@zu Please see above.

**Comment by zu** [comment]
Hi @cdevroe 

I'm not sure, if base_url was set.

But the problem most likely was, that I had a micture between http & https
