### ISSUE TITLE
Feature: LDAP Authentication. Or other method to manage many users in unmark

### ISSUE THREAD

**Issue by moltenkaizen** [plainmade/unmark#169]
We're experimenting with unmark to deploy for 800 users.

LDAP Auth would be really amazing.

If that's too much to ask, perhaps adding users with some sort of admin management web UI.

What is the hashing method in the users table in the db? Worst case, I might be able to bulk import users with a script to INSERT directly into that table.

**Comment by cdevroe** [comment]
@moltenkaizen We have our own build of Unmark that has some basic user management for unmark.it however we do not have that code in an open repository.

Of course, there are ways to add more uses. There are config variables specifically suited to turning on user registration and, as you can see in the code, there are methods for adding users such as https://github.com/plainmade/unmark/blob/master/application/controllers/register.php#L22

If you built an extension you could very likely import those 800 users without too much effort.
