### ISSUE TITLE
installation troubles

### ISSUE THREAD

**Issue by tulkraykja46jdg** [plainmade/unmark#176]
Ubuntu 14.04
php 5.5
Apache 2.4.7
gettext enabled
mysql Ver 14.14 Distrib 5.5.47
0 codeigniter knowledge/experience
unmark extracted to /var/www/html/unmark

unmark.site.net.conf
```
<VirtualHost *:80>
    ServerName unmark.site.net
    DocumentRoot /var/www/html/unmark/

<Directory /var/www/html/unmark/>
        Options Indexes FollowSymLinks
        AllowOverride FileInfo
        Require all granted
</Directory>
</VirtualHost>
```

Why can't i get unmark working?
1. downloaded lastest zip, 1.7.11 and extracted to /var/www/html/unmark
2. chown -R www-data:www-data /var/www/html/unmark
3. created db and db user, granted db user permissions to db
4. copied database-sampe.php to database.php
5. edited the following lines, leaving the rest in tact: `$db['default']['username'], $db['default']['password'], $db['default']['database']`
6. made new subdomain
7. made new apache site.conf with the above minus the `<directory />` part
8. went to unmark.site.net but nothing loaded, found that extra bit of config on another issue and added it in, reloaded apache
9. refreshed website, favicon now loads but index.php is just blank as well as /setup, nothing in f12 or logs

trying unmark.site.net/cronjobs gets the unmark page not found with the red cross and going to /cronjobs.txt loads it ( just an example, happens to other files too)
i can post phpinfo?

This is annoying me so much, i thought it'd be a 5-10 minute job to get this up and running but it's been over an hour now 😢. 
Also IE/Edge keep throwing a 500 error at unmark.site.net unlike ff/chrome.

Any help would be grand.

**Comment by cdevroe** [comment]
@tulkraykja46jdg  
Why would you try to load the cronjobs file? 

Try /setup

**Comment by tulkraykja46jdg** [comment]
@cdevroe 

Just to see if anything loads under unmark.site.net, as i said it was an example, unmark.site.net and unmark.site.net/setup just loads a blank page.

**Comment by cdevroe** [comment]
Update index.php and have the "environment" variable set to "development" then run /setup and then give us the files in /application/logs

**Comment by cdevroe** [comment]
Also, can you make sure in the Unmark root that you have a .htaccess file? If not: Use this one

https://raw.githubusercontent.com/plainmade/unmark/master/.htaccess

**Comment by tulkraykja46jdg** [comment]
i already tried by changing production logging to "4".
But changed index.php to development, and here's what you asked for:
```
root@system:/# ls -alrt /var/www/html/unmark/application/logs/
total 20
-rwxr-xr-x  1 www-data www-data  114 Oct  7 00:11 index.html
drwxr-xr-x 16 www-data www-data 4096 Oct  7 00:11 ..
drwxr-xr-x  2 www-data www-data 4096 Oct  7 01:12 .
-rw-rw-rw-  1 www-data www-data 7297 Oct  7 16:06 log-2016-10-07.php
root@system:/# > /var/www/html/unmark/application/logs/log-2016-10-07.php
root@system:/# cat /var/www/html/unmark/application/logs/log-2016-10-07.php
root@system:/# w3m -dump http://unmark.site.net/setup
root@system:/# cat /var/www/html/unmark/application/logs/log-2016-10-07.php
DEBUG - 2016-10-07 16:10:43 --> Config Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Plain_Config Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Hooks Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Plain_Hooks Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Utf8 Class Initialized
DEBUG - 2016-10-07 16:10:43 --> UTF-8 Support Enabled
DEBUG - 2016-10-07 16:10:43 --> URI Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Router Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Plain_Router Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Output Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Security Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Input Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Global POST and COOKIE data sanitized
DEBUG - 2016-10-07 16:10:43 --> Language Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Loader Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Plain_Loader Class Initialized
DEBUG - 2016-10-07 16:10:43 --> Config file loaded: application/config/all/app.php
DEBUG - 2016-10-07 16:10:43 --> Helper loaded: data_helper
DEBUG - 2016-10-07 16:10:43 --> Helper loaded: hash_helper
DEBUG - 2016-10-07 16:10:43 --> Helper loaded: validation_helper
DEBUG - 2016-10-07 16:10:43 --> Helper loaded: view_helper
DEBUG - 2016-10-07 16:10:43 --> Helper loaded: url_helper
DEBUG - 2016-10-07 16:10:43 --> Database Driver Class Initialized
root@system:/#
```
Yes i have .htaccess
```
root@system:/# ls -al /var/www/html/unmark
total 176
drwxr-xr-x  7 www-data www-data  4096 Oct  7 01:23 .
drwxr-xr-x  5 root     root      4096 Oct  7 01:52 ..
drwxr-xr-x 16 www-data www-data  4096 Oct  7 00:11 application
drwxr-xr-x  7 www-data www-data  4096 Oct  7 00:11 assets
drwxr-xr-x  2 www-data www-data  4096 Oct  7 00:11 bookmarklets
-rwxr-xr-x  1 www-data www-data   176 Oct  7 00:11 cronjobs_live.txt
-rwxr-xr-x  1 www-data www-data   196 Oct  7 00:11 cronjobs.txt
drwxr-xr-x  2 www-data www-data  4096 Oct  7 00:11 custom_example
-rwxr-xr-x  1 www-data www-data  2470 Oct  7 00:11 export-schema.md
-rwxr-xr-x  1 www-data www-data 99678 Oct  7 00:11 favicon.ico
-rwxr-xr-x  1 www-data www-data   360 Oct  7 00:11 .gitignore
-rwxr-xr-x  1 www-data www-data  4012 Oct  7 00:11 Gruntfile.js
-rwxr-xr-x  1 www-data www-data  1221 Oct  7 00:11 .htaccess
-rwxr-xr-x  1 www-data www-data  7073 Oct  7 16:05 index.php
-rwxr-xr-x  1 www-data www-data  3629 Oct  7 00:11 license.txt
-rwxr-xr-x  1 www-data www-data   463 Oct  7 00:11 package.json
-rwxr-xr-x  1 www-data www-data  5884 Oct  7 00:11 readme.md
drwxr-xr-x  8 www-data www-data  4096 Oct  7 00:11 system
root@system:/#
```

**Comment by cdevroe** [comment]
Setup screen still white? I don't see any errors.

**Comment by tulkraykja46jdg** [comment]
yep, still white/blank.

**Comment by tulkraykja46jdg** [comment]
any ideas?

**Comment by tulkraykja46jdg** [comment]
You can close this as i've fixed it now, edited some of the php, also edited some code to allow username instead of email as this will be selfhosted for myself only, don't need the email functionality etc.

**Comment by cdevroe** [comment]
"Edited some of the PHP" ??

It would be great if you could share what you needed to change in order to get Unmark working for you. Thank you.
