### ISSUE TITLE
Support for several users

### ISSUE THREAD

**Issue by mclang** [plainmade/unmark#190]
I'm stumbled.

I was thinking to put up my own unmark server so that whole family could create users and make some sense to their bookmark mess, but the basic installation seems to support only one user.

Is there a way around this, e.g manually creating users into the database?

**Comment by f-r-e-e-s-k-y** [comment]
You can add users manually in the db, but I stumbled upon a "register" view in the file tree, which seems to be the official way. So all you need to do is open your browser and point it to _https://your-unmark-installation-url_**/register**

**Comment by mclang** [comment]
Thanks, this works!
