### ISSUE TITLE
Ability to add tags to bookmarks

### ISSUE THREAD

**Issue by weaktyper** [plainmade/unmark#196]
Does anyone know if it is possible to

- add tags to each link
- modify tags to each link

Also, what is the difference between a label and a tag?

**Comment by virtadpt** [comment]
If by that you mean "when adding a new link," the answer is yes, just hashtag them.  If you mean "after a link has been added and you're editing it," the answer is also yes (but it's a little pixel-twitchy): Click on the link's entry beneath the title but to the left of the "archive this link checkmark" button.  The link's entry will appear in the right-hand column.  Click on the "Notes (click to edit)" bar and edit the link's description, including any hashtags if you like.  Click on the "Editing mark info" bar when you're done to save the edits.

**Comment by weaktyper** [comment]
@virtadpt 
Thanks for the reply, that helped greatly. 
I can now 
- add a tag 
- modify tags on a link.

So about labels, what are they useful for. There are some predefined labels that don't suit my usecase, can labels be 
-added or 
removed ?

**Comment by weaktyper** [comment]
closing as question about tags answered, opening separate query about issues in #200.

**Comment by virtadpt** [comment]
To the best of my knowledge, labels cannot be added or removed.  I don't find them very useful, either, so I just ignore them.
