### ISSUE TITLE
Import from Other?

### ISSUE THREAD

**Issue by ZicklePop** [plainmade/unmark#45]
The Unmark help page says you can [import bookmarks](http://help.unmark.it/import-export) from Pinboard and other services, but the self-hosted version from here on GitHub does not seem to have an `Import from Other` feature.

**Comment by nothing-fr** [comment]
nice, I'm thinking about migrating from [Shaarli](https://github.com/sebsauvage/Shaarli)
 to Unmark... but i need this feature ! ;)

Have too much bookmarks right now to migrate manually...

**Comment by cdevroe** [comment]
@nothing-fr Right now http://unmark.it - the hosted solution - allows for importing bookmarks from Browsers (Safari, Chrome, etc.), Pinboard, and Delicious.

We'd love it if someone extended the importer to support other services... Shaarli included!
