### ISSUE TITLE
/setup redirects to root

### ISSUE THREAD

**Issue by jayarathina** [plainmade/unmark#57]
I am trying to install unmark in my local system.

I have the files extracted to .../xampp/htdocs/c

I have modified /application/config/database.php as

```
if ($_SERVER['HTTP_HOST'] == 'localhost') { // If local, load this
  $db['default']['hostname'] = 'localhost';
  $db['default']['username'] = 'root';
  $db['default']['password'] = '';
  $db['default']['database'] = 'unmark';

} else { // If not local, load this
  $db['default']['hostname'] = 'localhost';
  $db['default']['username'] = 'root';
  $db['default']['password'] = '';
  $db['default']['database'] = 'unmark';

}
```

(unmark is the db name. It does exist)

When i try to access http://localhost/c/setup it is redirecting to http://localhost/xampp/

The log file is empty. :worried:

What am I doing wrong? Please help.

(p.s: May be solution for issue[https://github.com/plainmade/unmark/issues/30] can help resolve my issue?)

**Comment by ParikhKadam** [comment]
@jayarathina Did it solve the issue? Bcoz it didn't for me... Need help here - https://github.com/cdevroe/unmark/issues/254
