### ISSUE TITLE
Account creation & login

### ISSUE THREAD

**Issue by Kasparov51** [plainmade/unmark#64]
Hello,

I'm still trying to get unmark working on my website :)

Since my last issue I managed to make unmark to get installed properly (well I think so).
On the account creation screen, I always have an "Unexpected error", and the error log tells : 
ERROR - 2014-10-14 13:22:21 --> Query error: (yes, nothing here)

Whatever the passwords, I always have the red block saying the two passwords don't match, but when I create an account with a password including 1 caps, 1 number, and 8 chars, there is an insert in the Users table.

Then, when I try to login, I have the screen with the circle, then I get back to the login screen, and still only this error :
ERROR - 2014-10-14 13:24:13 --> Query error: (yes, still nothing here)

I'm kinda out of clues now, if someone could give a hand, it would be great.

Thank you.

**Comment by williamknauss** [comment]
Hi @Kasparov51,
The technical requirements of Unmark require PHP 5.4. I see you listed PHP 5.2.17. Maybe this is the cause of the mysql and other issues you are having? Any chance you could update to PHP 5.4 and see if you still have these problems?

**Comment by Kasparov51** [comment]
Hello,

Thank you for the answer.
I'm currently trying to make the server version update to 5.4 or higher.
I'll try again as soon as possible.

**Comment by Kasparov51** [comment]
So I now have PHP 5.4.
I have the right error messages on login, I can connect smoothly, and the link's categories color dots seems to work correctly. I'll try a new install tonight (as I made many modifications on this one to understand what was going wrong) and I'll confirm the tickets that can now be closed.
Thank you :)

**Comment by Kasparov51** [comment]
By using PHP 5.4, everything is fine now.
