### ISSUE TITLE
Support for disabling registrations?

### ISSUE THREAD

**Issue by rpdillon** [plainmade/unmark#67]
On a private server, I don't see a way to disable registrations after all intended users have been added.  I looked through the wiki and code a bit, and even tried disabling the routes for registration, but hostname.tld/register still presents a form for new users to register.

Is there a setting I'm missing?

**Comment by williamknauss** [comment]
Hello @rpdillon,
I added this feature in [my branch] (https://github.com/williamknauss/unmark/tree/issue-67).
Its simple enough to use, just set the config value 'plain_enable_registrations' to true of false in ./application/config/config.php.

@cdevroe should I open a PR to the master or staging branch?

**Comment by cdevroe** [comment]
@williamknauss This looks to be a simple enough solution. Perhaps also adding a note in the Readme for how to update the config. Then make a PR.

**Comment by williamknauss** [comment]
Hi @rpdillon,
We have implemented this feature in the most recent version of Unmark. Download the [newest master branch.] (https://github.com/plainmade/unmark/archive/master.zip)

Thanks Mate

**Comment by rpdillon** [comment]
On February 13, 2015 12:57:44 PM PST, William Knauss <notifications@github.com> wrote:
>Hi @rpdillon,
>We have implemented this feature in the most recent version of Unmark.
>Download the [newest master branch.]
>(https://github.com/plainmade/unmark/archive/master.zip)
>
>Thanks Mate
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/plainmade/unmark/issues/67#issuecomment-74325599

Awesome!  I'll check it out this weekend.  Thanks!
-- 
Sent from mobile.
