### ISSUE TITLE
Labels not working ?

### ISSUE THREAD

**Issue by Kasparov51** [plainmade/unmark#68]
Hello, it's me again :)

Now that I can play with the app, I encounter another problem : the labels are not working.

In other words, when I try to open the slide down menu with the labels (well, I assume it's a slide down menu, as it's not working...), I have the label currently set, then a blank line, then nothing else. So with a new mark, I have only the "Unlabeled" Label, and a blank line, and with the marks already saved, I only have the "Do" Label, and a blank line.

I have the problem in the popup (via the bookmarklet) as well.

Before asking, no, I don't have the slightest entry in the log file :)

Thank you for your help.

**Comment by williamknauss** [comment]
Hi @Kasparov51,
In a previous bug report you mentioned using PHP version 5.2.17. Are you using the same version of PHP when filing this report?

Thanks Mate

**Comment by Kasparov51** [comment]
By using PHP 5.4, everything is fine now.

**Comment by williamknauss** [comment]
@Kasparov51 
Great to hear mate! 

Cheers!
