### ISSUE TITLE
could not register a user after setup

### ISSUE THREAD

**Issue by cybrwushl93** [plainmade/unmark#71]
When I setup unmark, all tables were created, but I'm not able to register my user.
The only response was a red bar under the form with no text in it.
The log files were empty, even after setting error_reporting to E_ALL ...
I used finally the milestone-1.6 branch.

**Comment by williamknauss** [comment]
@cybrwushl93,
The behavior you are listing sounds like you might be using an older version of PHP. Can you confirm you are using PHP 5.4 or above?

Thanks mate

**Comment by cybrwushl93** [comment]
@williamknauss 
I definitly using php version 5.5.9.

After your reply I made a fresh installation on my ubuntu server from the master branch and nothing of the above happened! I could register a user and work fine with unmark.

Thanks for your support.

**Comment by vits** [comment]
Hi, got this problem and found the reason, at least in my case. If you don't have mod_rewrite enabled for Apache, everything *almost* works, registration form is shown and can be submitted, but returns error shown in above image. Enabled mod_rewrite and everything works fine.
