### ISSUE TITLE
Make db error messages explicit

### ISSUE THREAD

**Issue by su** [plainmade/unmark#76]
There's a file at `application/errors/error_db.php` intended for calling out database errors to the user, which currently contains a hard-coded generic "unexpected error" message. 

This should at the very least indicate the *type* of error if it remains hard-coded, though ideally would return the actual error involved, such as gets written to the log when the application can't connect to the database, which seems to be the problem with all those people who can't get their self-installs going. (More on that in a separate issue.)

**Comment by cdevroe** [comment]
Myself, or someone that is willing, will need to hop on this to close out 1.6.2. I think this is needed in Unmark to resolve a lot of issues people are having.

**Comment by williamknauss** [comment]
Hello @su,
Well there is a couple of ways of going about this. Once the default ENVIRONMENT in ./index.php could be changed from "production" to "development", which when then display the errors you are requesting.

There is also the possibility of removing the if/else statement in the error(s) file(s) and to always show the heading and message.

Another option although more complex could be to only show the errors if the application hasn't been installed yet.

What are your thoughts @cdevroe

**Comment by williamknauss** [comment]
@cdevroe I would be glad to submit a PR for this if you want.

**Comment by williamknauss** [comment]
I lean towards showing errors only if one of the following conditions if met.
A) The developer has specifically set errors to show
B) The application hasn't been installed yet

**Comment by cdevroe** [comment]
Perhaps we can do something a bit nicer than the default messaging... perhaps we can return the error(s) that CodeIgniter would return normally... and put them into the current view in Unmark so that they are styled nicely.

**Comment by williamknauss** [comment]
This would be as simple as removing the if/else in the error views I believe. Keep in mind though that these error messages would still be displayed in a production environment.

**Comment by cdevroe** [comment]
@su  pull the latest master branch and give it a whirl. Then come back and let @williamknauss and I know if you need anything else.

**Comment by williamknauss** [comment]
@cdevroe,
We may have to do the same logic change to ./application/errors/error_general.php.

**Comment by cdevroe** [comment]
@williamknauss Good point. Done.

**Comment by williamknauss** [comment]
@su,
The are errors are now verbose on all ENVIRONMENTS. Thanks for pointing this out.
