### ISSUE TITLE
What's the purpose of the if/else in database.php?

### ISSUE THREAD

**Issue by su** [plainmade/unmark#77]
There are several people who have, or had, problems doing self-installs, many of which seem to involve not realizing they aren't connecting to their database(see #76 ) That's also how I ended up here, for that matter. 

I spent some time earlier creating a db user over and over with different host values to figure out why that was and found some things out, but the more I looked at it, the more it seems like it's just various small confusions interacting with each other. Besides some bits in the documentation, they center on this: 

    if ($_SERVER['HTTP_HOST'] == 'localhost') { // If local, load this
      $db['default']['hostname'] = '127.0.0.1';
      $db['default']['username'] = 'root';
      $db['default']['password'] = 'root';
      $db['default']['database'] = 'unmark';
    } else { // If not local, load this
      $db['default']['hostname'] = 'localhost';
      $db['default']['username'] = 'username';
      $db['default']['password'] = 'password';
      $db['default']['database'] = 'unmark';
    }

Things potentially in a user's head here:
* Why are there two blocks of db info? [This is weird and the docs make no reference to it.]
* Which do I fill out? Based on what? [As above.]
* What happens if I just fill out both? [Meh.]
* What does "if local" mean? [The test is about the browser URL, but the *info* is about the db.]
* My install is "local" (on my machine) but at the domain something.local. Now what? [Turns out this goes to the else and makes it seem like the if always fails.]
* …and so on.

But as far as I can tell nobody should have to think about *any* of that.
Unless I'm not seeing something—he says before being brutally shot down—the conditional doesn't seem to "do" anything other than let you assume the db hostname is 127.0.0.1 in one specific case, even though localhost is the default value for the other case, anyway. If you just make the user always provide the hostname, the whole thing collapses into a few simple variable declarations.

Is there something else going on?

**Comment by cdevroe** [comment]
@su You're right. This is probably superfluous and could easily confuse someone that is new to PHP or database setups. We had this logic simply to allow both for local development and pushing to a remote server. However, I'm guessing that in most cases people that use Unmark locally aren't deploying it anywhere.

This logic could be removed from the sample file. No doubt.

**Comment by williamknauss** [comment]
CodeIgniter will automatically load configuration based on your ENVIRONMENT. 
I.e. if your ENVIRONMENT is set to development then CodeIgniter will first check to see if ./application/config/development/database.php exists and if it doesn't CodeIgniter will fallback to ./application/config/database.php
