### ISSUE TITLE
Can't Login after setup 1st User

### ISSUE THREAD

**Issue by githubtobi** [plainmade/unmark#79]
I installed unmark under bookmark.domain.tld, did the /setup routine and added the first user.

The user was creasted successful ("You are now registered, logging you in..."

But login is not possible, loading-icon appears and after a few seconds redirect to the login-screen.

There's also an error message when I want to do the forgot-password-function: "Email not recognized". In the DB I can see the user in the users-table with the address entered in the forgot-password-form.

Best,
Tobi

**Comment by cdevroe** [comment]
@githubtobi See if this is related https://github.com/plainmade/unmark/issues/31#issuecomment-68490138

**Comment by cdevroe** [comment]
@githubtobi Have you solved this issue yet? Have you looked in the database to see if the user is created?

**Comment by williamknauss** [comment]
Hi mate, @githubtobi
Would you mind telling us the PHP version you are using?

Thanks Mate

**Comment by githubtobi** [comment]
Hi @cdevroe , @williamknauss ,

I fixed the issue yesterday by using another webhoster (uberspace). It works now - cool!

Will try to install it on my local server with debian, nginx and mysql next week.

Tobi

**Comment by yforster** [comment]
I failed many times installing unmark in my uberspace. I would be very grateful if you could drop me an email (via my profile) and tell me if you did anything special to install unmark.

**Comment by williamknauss** [comment]
Hello @yforster,
While this ticked is closed, I'll try to answer your question in one response. If it takes more than one response I would kindly ask you open your own issue. I would suggest downloading the newest [master branch] (https://github.com/plainmade/unmark/archive/master.zip) and try installing with that. Some changes were made recently that may affect your installation environment.

**Comment by githubtobi** [comment]
Hi yforster,

sure, will drop you a mail in a minute how to install unmark on uberspace. It's a bit tricky but at the end it works perfectly!

Tobi

**Comment by williamknauss** [comment]
@githubtobi,
Just for kicks and giggles would you mind posting the instructions here, so we can get them added to the wiki?

Thanks Mate

**Comment by githubtobi** [comment]
sure:

1.) Connect to your uberspace account via SSH & add the bookmark subdomain (uberspace-add-comain -d bookmark.domain.tld -w)
2.) Configure Subdomain in your account of your domain registrar - I use inwx.de  (select domain, dns-entry, new -> bookmark, A, uberspace IP)
5.) Connect to uberspace via ssh and change to your html folder "cd /var/www/virtual/<username>/html"
6.) Download unmark-zip file from github (wget...)
7.) Unpack ZIP File ("unzip unmark-master.zip")
8.) Rename folder "mv unmark-master bookmark"
9.) delete zip-file "rm unmark-master.zip"
10.) Create a Symlink to your folder in the web root "ln -s /var/www/virtual/<username>/html/bookmark bookmark.domain.tld"
11.) Create a SQL database 
12.) Start unmark setup http://bookmark.domain.tld/setup

That's it. You can access unmark at http://bookmark.domain.tld

Tobi

**Comment by cdevroe** [comment]
@williamknauss @githubtobi I wonder if this would be good to add to the wiki so people can reference it?

**Comment by githubtobi** [comment]
No prob, just copy & paste my text

**Comment by cdevroe** [comment]
Thanks @githubtobi I put this here:
https://github.com/plainmade/unmark/wiki/How-to-use-Unmark-on-Uberspace
