### ISSUE TITLE
/setup Error... There isn't a setup

### ISSUE THREAD

**Issue by iampariah** [plainmade/unmark#80]
I'm trying to install Unmark on my test server, and I've followed the installation instructions right down to "Point your browser to your-unmark-url/setup" . There isn't a setup file in the root of releases 1.6 or 1.6.1. The only setup is application/views/setup.php, but trying to execute that gives me a 503 forbidden error. What am I doing wrong?

**Comment by cdevroe** [comment]
@iampariah What is your level of expertise with CodeIgniter applications?

**Comment by iampariah** [comment]
Complete novice--never used Codeigniter. I had thought Unmark was a simple PHP/MySQL install. Am I out of my depth?

I want to host my own Unmark because I've had too many Web services I rely on go belly up or change features I find crucial (Diigo, Delicious, Digg, StumbleUpon, etc.).

**Comment by cdevroe** [comment]
> "I want to host my own Unmark because I've had too many Web services I rely on go belly up" 

This is precisely why we open sourced Unmark from the beginning. And it is OK that you're a novice, I just figured I'd ask.

/setup isn't a folder you'd see included with the application. You'll notice in /application/config/routes.php that many routes have been specified so that specific URL structures run specific controllers/methods. In /setup - you can see that it runs the method "setup" inside the install controller in /application/controllers/install.php -- From there the method calls the "setup" view that you specified. This, really, just ends up giving you a button to click called "Install".

If you are getting an error on this first step, our guess is that your database information may be incorrect. This is found in /application/config/database.php

First step, check those credentials.

**Comment by iampariah** [comment]
Thanks for your patience, Colin.

When I visit http://[mydomain]/unmark/ the error I get is /application/errors/error_db.php (I change the title to differentiate it from error_general.php to be sure). So, I'm getting a db connection problem, right? How do I fix this?

I have an empty MySQL 5.1 db with a working user account (can log in via PHPMyAdmin). In application/config/database.php I have the following. Have I misconfigured it?

    if ($_SERVER['HTTP_HOST'] == 'localhost') { // If local, load this
      $db['default']['hostname'] = '127.0.0.1';
      $db['default']['username'] = 'root';
      $db['default']['password'] = 'root';
      $db['default']['database'] = 'unmark';
    
    } else { // If not local, load this
      $db['default']['hostname'] = 'mysql65-029.wc1.dfw1.stabletransit.com';
      $db['default']['username'] = 'MyUnmarkUsername';
      $db['default']['password'] = 'MyUnmarkUserPassword';
      $db['default']['database'] = 'MyUnmarkDB'';
    
    }

(The hostname is the format all other PHP scripts work with on Rackspace Cloud server; "localhost" doesn't work.)

**Comment by iampariah** [comment]
I've tried a number of different configurations on this with no luck.

**Comment by leirags** [comment]
I found some fixes, the codeigniter was not able to find the correct URL, then
edit application/config.php and set
The templates was designed to be the root of web page, 
and in my case thas was not correct, 
then fixit deleting the back slash caharacter from templates if tyou see "/assets/..." leave "assets/"
and that make to work.
Before install was necesary créate a Database in mysql, and set as "iampariah" says

**Comment by iampariah** [comment]
I don't quite understand. I should remove the leading "/" from all the addresses in application/config.php?

**Comment by leirags** [comment]
After a few hours dont work at all

Enviado desde mi iPhone

**Comment by iampariah** [comment]
I will gladly pay for a yearly sub to Unmark if I can just get this self-hosted version working.

**Comment by heubergen** [comment]
Have here the same problem, my details:
apache 2.4.10
mySQL 5.5.40
Debian 8
my database details:
<pre><code>if ($_SERVER['HTTP_HOST'] == 'localhost') { // If local, load this
  	$db['default']['hostname'] = 'localhost';
  	$db['default']['username'] = 'root';
  	$db['default']['password'] = '*5al]sTeDCIi';
  	$db['default']['database'] = 'unmark';

} else { // If not local, load this
  	$db['default']['hostname'] = 'localhost';
 	 $db['default']['username'] = 'root';
  	$db['default']['password'] = '*5al]sTeDCIi';
  	$db['default']['database'] = 'unmark';

}

$db['default']['dbdriver'] = 'mysql';
// $db['default']['dbprefix'] = ''; # Do not use, see: https://github.com/plainmade/unmark/issues/62
$db['default']['pconnect'] = TRUE;
$db['default']['db_debug'] = TRUE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'latin1';
$db['default']['dbcollat'] = 'latin1_swedish_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = TRUE;
$db['default']['stricton'] = FALSE;
$db['default']['timezone'] = ''; // GMT
</code></pre>
I check every setting, include char_set and dbcollat.
PHP requirements are installed and I use version 5.6.4

**Comment by iampariah** [comment]
{sigh} Rackspace cited some kind of security issue with MySQL 5.5 and their Cloud Site systems. They're "evaluating" 5.6. In the meantime, I paid for a year of hosted Unmark.it.

**Comment by heubergen** [comment]
Please reopen, the bug still exist!

**Comment by cdevroe** [comment]
@heubergen What is the bug?

**Comment by heubergen** [comment]
@cdevroe How you can on #84 I become a 404 not found error when I navigate to todo.***.ch/setup
I use apache, mysql and php.

**Comment by cdevroe** [comment]
If there is a 404 in Unmark ever there is an error in the set up. Please let us know your logs on #84

**Comment by leirags** [comment]
I try again and make a log id changes next monday send TO you

Enviado desde mi iPhone
