### ISSUE TITLE
preview function on self hosted unmark

### ISSUE THREAD

**Issue by w00kie** [plainmade/unmark#81]
Hello,

I just installed Unmark on my server. I see some files detailing crontabs related to embeds but no info in the install manual. I signed up to http://embed.ly and put my API key in `application/config/all/app.php` but I sill see no preview for my marks.

Is that feature only active in the hosted version?

Keep up the good work,
Regards,
Francois

**Comment by w00kie** [comment]
Alright, turns out I was expecting *any* link to have a preview, but it's only stuff like youtube, instagram and a limited list of such websites. Any reason for that? Since embed.ly looks like it can process pretty much any link...

For other people looking for the cron, it seems you must run `php index.php cron processEmbeds`

**Comment by cdevroe** [comment]
@w00kie We like to be selective with this feature. We think it adds value in many circumstances, but takes away in others. Feel free to modify your copy to process every URL.

**Comment by w00kie** [comment]
Thanks for the reply @cdevroe. I've edited `application/helpers/oembed_helper.php` to process all pages and save at least the description to the preview. Now one feature that would be nice would be to use the description also for the search.

**Comment by cdevroe** [comment]
@w00kie Feel free to make some edits and do a Pull Request. We'd love to be able to search description too.

**Comment by w00kie** [comment]
I looked into adding fulltext search but it would require either adding a new myisam table for indexing or upgrading to mysql 5.6

**Comment by domib** [comment]
Hi everyone! @w00kie , could you post your changes to process more pages? Would be very nice :)

**Comment by w00kie** [comment]
Sure, I have a branch with this enable on my fork, it's really a small change: https://github.com/plainmade/unmark/compare/master...w00kie:embed-all

You also need to get an http://embed.ly/ API key and put it in your config file.
