### ISSUE TITLE
[SOLVED] An unexpected error has occured after clicking install

### ISSUE THREAD

**Issue by bitsandnumbers** [plainmade/unmark#82]
Hi,

I'm trying to setup unmark on my freebsd server.

So I followed all the dependency requirements, configured the database.php file (both sections have the same credentials) and made sure that all permissions were ok. I checked my mysql setup, and have a user registered both on localhost and 127.0.0.1, with all privileges granted to the unmark database.

When I click on the install button, I get "An unexpected error has occured" with no logs whatsoever.

So I assume that when I click install, unmark tries to populate the db, so it must not be a dependency issue. There is one table in the database though, called "migration". Dunno if it was there before ?

I can provide you any info wanted, but I'm kind of stuck here without any logging … Any help appreciated. Thx

**Comment by bitsandnumbers** [comment]
SOLUTION:
Never mind. So my issue was that my mysql setup was using mysqli, so I had to change the dbdriver and install php-mysqli extension. Now it works :-)

**Comment by cdevroe** [comment]
@bitsandnumbers Glad you found your issue and thanks for taking the time to report it.
