### ISSUE TITLE
Upgrade issue: Direct upgrade from 1.5.2 to 1.6.1 breaks things.

### ISSUE THREAD

**Issue by nitinthewiz** [plainmade/unmark#83]
Hi, I tried to upgrade today on my personal setup from 1.5.2 to 1.6.1 and the generic "Eek something wrong" error came.

While browsing other issues, I discovered the logs sitting under /application/logs (you should include this in the debug steps in the ReadMe...

In there, I discovered the following - 
> ERROR - 2015-01-14 17:27:25 --> Query error: Unknown column 'users_to_marks.mark_title' in 'field list'
> ERROR - 2015-01-14 17:28:07 --> Query error: Unknown column 'users_to_marks.mark_title' in 'field list'
> ERROR - 2015-01-14 18:53:30 --> Query error: Unknown column 'users_to_marks.mark_title' in 'field list'
> ERROR - 2015-01-14 19:00:47 --> Query error: Unknown column 'users_to_marks.mark_title' in 'field list'

So, I looked for 'users_to_marks.mark_title' in the code using GitHub's trusty code search and found that there's an Alter table command adding that col in the migrations file. Clearly, that had crapped out. So, I went to my PHPMyAdmin and ran the command and voila! Everything works.

This is a bug. Please look into it. I can't say any further because the setup is on shared hosting and I don't have access to the PHP logs (I know right? What is nosupportlinuxhosting even thinking?!).

Also, please close the bug as I've fixed it in my setup. 

Thank you for reading! :smile:

**Comment by cdevroe** [comment]
@nitinthewiz We don't mention where the logs are because we try to state, fairly clearly, that this uses Code Igniter. So we hope people will visit http://www.codeigniter.com/docs often to see how they should work on Unmark.

I wish we knew what the error was in your upgrade. A simple migration should have worked just fine. Can you see if the current migration version (stored in DB) is up-to-date with what the configuration says? BTW, the upgrade URL is /upgrade for Unmark. This is what runs migrations.

**Comment by nitinthewiz** [comment]
@cdevroe hmmm. Yes, I should use CodeIgniter docs to figure that out. Next time! 

Now, deets. Currently, the migrations table says version 10.

And yes, I ran /upgrade, which redirected to /marks and the generic error was displayed. I don't have a local setup to repro the issue but I'll keep my eyes open next time...

Also, "nilaywillmakemoney"? :stuck_out_tongue_closed_eyes:

**Comment by williamknauss** [comment]
Hi @nitinthewiz,
I'm a bit confused here. Were you able to solve the problems you had? If not could you provide your PHP version that your using?

**Comment by nitinthewiz** [comment]
@williamknauss I was able to resolve the issue by running that MySQL Alter table command manually. It did not run on it's own no matter what I tried. As for the PHP version, it is PHP 5.4.31 as listed [here](http://www.nosupportlinuxhosting.com/ServerSpecs.html).

**Comment by cdevroe** [comment]
@nitinthewiz Glad you were able to resolve your issue. Odd that the migration didn't run. I wish the migrations we were using were more robust and easier to manage.
