### ISSUE TITLE
/setup Error... Not Found

### ISSUE THREAD

**Issue by heubergen** [plainmade/unmark#84]
When I try to configure unmark on my root server I can't access the first setup.
I just become a "404 Not Found" error and can't use the application.

Here my details:
apache 2.4.10
mySQL 5.5.40
Debian 8
PHP 5.6.4
my database details:
<pre><code>if ($_SERVER['HTTP_HOST'] == 'localhost') { // If local, load this
  	$db['default']['hostname'] = 'localhost'; # also test it with 127.0.0.1
  	$db['default']['username'] = 'root';
  	$db['default']['password'] = '***';
  	$db['default']['database'] = 'unmark';

} else { // If not local, load this
  	$db['default']['hostname'] = 'localhost';
 	 $db['default']['username'] = 'root';
  	$db['default']['password'] = '***';
  	$db['default']['database'] = 'unmark';

}

$db['default']['dbdriver'] = 'mysql';
// $db['default']['dbprefix'] = ''; # Do not use, see: https://github.com/plainmade/unmark/issues/62
$db['default']['pconnect'] = TRUE;
$db['default']['db_debug'] = TRUE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'latin1';
$db['default']['dbcollat'] = 'latin1_swedish_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = TRUE;
$db['default']['stricton'] = FALSE;
$db['default']['timezone'] = ''; // GMT
</code></pre>
I check every setting, include char_set and dbcollat.
PHP requirements are installed.

**Comment by cdevroe** [comment]
Can you paste your application logs here?

**Comment by heubergen** [comment]
Sorry, Im not sure which log you mean?
I have here Apache, mysql or do you mean a other?
The error_log file in unmark is empty.

**Comment by cdevroe** [comment]
@heubergen Looks like the database isn't being set up. Or the user you're using doesn't have permissions. Or the database itself doesn't exist.

Can you do a test PHP file to connect to the database to make sure you have everything correct?

Something like
```
mysql_connect($db_host,$db_username,$db_pass) or die ("could not connect to mysql");
mysql_select_db($db_name) or die ("no database"); 
```

**Comment by heubergen** [comment]
Hmmm, I become a "could not connect to mysql" back, does I have to initialize the database first?

**Comment by cdevroe** [comment]
@heubergen Try running setup again and see if any tables are created.

**Comment by heubergen** [comment]
@cdevroe Sorry, there are not created tables, I don't think that anything happen if I become a 404 error...

**Comment by chrtze** [comment]
+1

"The requested URL /index.php was not found on this server."

When trying to access /setup

**Comment by yforster** [comment]
+1 "The requested URL /index.php was not found on this server."

**Comment by williamknauss** [comment]
@heubergen
When I went thru the installation I also got a white page. After some debugging I found the whitepage was caused by not having gettext enabled in php. Could you verify that you do indeed have gettext installed and enabled?

**Comment by heubergen** [comment]
Thanks for your helping @williamknauss but I have install and enabled the extension.
In my php info stand follow:
gettext
GetText Support	enabled

**Comment by williamknauss** [comment]
@heubergen,
You've got me stumped here but I'm not giving up. Do you have access to the web server error log? If so could you clear the log(s), download the master branch again and try your install. If it still fails I would be very interested in seeing the web server error logs have to say.

**Comment by Menti** [comment]
I don't know if this could be useful, but I tried to install Unmask on a Bitnami LAMP stack (https://bitnami.com/stack/lamp) and it failed (it connected to MySQL but couldn't find the database). Since Bitnami is self-contained, I guess it should behave the same in any computer.

**Comment by williamknauss** [comment]
Hi @Menti,
Sorry to see you are having problems to. What version of PHP are you using?

**Comment by heubergen** [comment]
error.log:<pre><code>
[Thu Feb 05 18:46:00.176315 2015] [ssl:warn] [pid 2844] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 05 18:46:00.231702 2015] [ssl:warn] [pid 2845] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 05 18:46:00.235122 2015] [mpm_prefork:notice] [pid 2845] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1k configured -- resuming normal operations
[Thu Feb 05 18:46:00.235162 2015] [core:notice] [pid 2845] AH00094: Command line: '/usr/sbin/apache2'</code></pre>

other_vhosts_access.log :<pre><code>
todo.z33.ch:80 212.51.154.12 - - [05/Feb/2015:18:47:12 +0100] "GET /setup HTTP/1.1" 404 497 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36"
todo.z33.ch:80 212.51.154.12 - - [05/Feb/2015:18:47:12 +0100] "GET /favicon.ico HTTP/1.1" 200 99981 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36"</code></pre>


The error still exist, above you see my logs until after I try to access the /setup.
I try it with the release 1.6.1

**Comment by Kasparov51** [comment]
Same problem here : trying to reinstall Unmark now that PHP version is 5.4, and /setup isn't working.
Same error as above : 
ERROR - 2015-02-05 18:50:43 --> Query error: Table 'unmark.plain_sessions' doesn't exist

**Comment by heubergen** [comment]
Thats sound like the app try to access a table that are not created first. Maybe the app should "initial" the database frist...

**Comment by williamknauss** [comment]
@heubergen,
Yes looks like we are making progress in debugging this. I just want to make sure you have enabled url rewrites. (mod_rewrite.so) As technically /setup isn't a file but a rewrite of /index.php/setup/index. From your logs it looks like you are using the mpm_php with Apache. I've honestly never tried it with the mpm, I've always used mod_php. Can you confirm so I can get diving into this? 

Thanks for your patience mate, we will get this sorted out I'm sure.

**Comment by heubergen** [comment]
I'm trying to bring mod_rewrite to work, I will ping you later.

**Comment by heubergen** [comment]
I have solved the problem!

My mod_rewrite was broken and I had to change something on etc/apache2/apache2.conf :
Old:
<pre><code>*Directory /var/www/*
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
*/Directory*</code></pre>
New:
<pre><code>*Directory /var/www/*
        Options Indexes FollowSymLinks
        AllowOverride FileInfo
        Require all granted
*/Directory*</code></pre>
Of course you have by the Directory instead of the "*" some "<" ">".

Thank goes to: @williamknauss
Ping to maybe solve the bug:
@chrtze @yforster @Kasparov51

I will not close the bug until some of the other say if its okay by them.

**Comment by cdevroe** [comment]
@heubergen @williamknauss This is awesome. I hope it solves the issue for many. Also... maybe we should add any of this information to our Wiki/Readme?

**Comment by heubergen** [comment]
Yeah I think its only a problem if you use the php-fpm package, with the default package (mod_php) you don't need to edit this setting if I'm right.

**Comment by Kasparov51** [comment]
I'm afraid my problem had nothing to do with that : on reinstalling Unmark, I had forgotten some tables of the previous install... Everything is working fine for me, now :)

**Comment by williamknauss** [comment]
@Kasparov51,
That's great to hear you got it work mate!

**Comment by williamknauss** [comment]
@chrtze and @yforster 
Can you confirm that the fixes listed here indeed solved your problem?

**Comment by williamknauss** [comment]
@heubergen,
Please correct me if I am wrong here, but the Apache directives (specifically the directory directives) you had to change would have needed changed whether you were running mod_php of php_fpm.

**Comment by heubergen** [comment]
I'm not shure, I can just say that in the past I had never have to change anything on this conf-file. So I think with the normal php modul it should work without any modification.

**Comment by yforster** [comment]
I was able to fix the error by accessing unmark via a subdomain. `http://example.com/unmark/setup` did not work, while `http://unmark.example.com/?setup` works.

**Comment by cdevroe** [comment]
@yforster You shouldn't need the ? in the URL.

**Comment by yforster** [comment]
Im sorry, your right, that's not needed. Is it intended behaviour that unmark is not accesible via folders?

**Comment by cdevroe** [comment]
@yforster If you installed it as a sub-domain, then that is why it is at unmark.*.* rather than *.*/unmark. I'm unsure how you installed it.

But yes, all routes should be domain.com/controller/method --- as this is a CodeIgniter application.

**Comment by yforster** [comment]
I am using uberspace.de and installed it to a subfolder, so example.com/unmark technically finds the index.php file, but I guess the CodeIgniter stuff does'nt work then. I can access this subfolder via a symlink as subdomain. Only the second way works. Maybe it would make sense to make this precise under the installation instructions.

**Comment by cdevroe** [comment]
It is not required that Unmark run as a sub-domain. I'm unsure about uberspace as I've never used it.

**Comment by heubergen** [comment]
I use uberspace in the past too :) @yforster 
@cdevroe uberspace is a hosting service where you have direct access to the shell via ssh and you can install and do everything for them you don't need a root account. You have also your own php.ini

**Comment by yforster** [comment]
I think this issue is not only uberspace related, but on any webserver we need the routes `domain.com/controller/method` as @cdevroe pointed out. Is this mentioned somewhere?

**Comment by cdevroe** [comment]
@yforster Unless I'm misunderstanding this thread... CodeIgniter does this out of the box. So any of the routes in /application/config/routes.php are custom.

**Comment by yforster** [comment]
So you'd suggest it is a bug that I get this error when accessing unmark via `domain.com/unmark`?

**Comment by williamknauss** [comment]
@yforster,
I have confirmed that installing Unmark in a sub directory doesn't work as expected. I'll open a new ticket an reference there issue number here.

Thanks Mate

**Comment by Menti** [comment]
The same installation that does not work if accessed as a subdirectory works if accessed as a subdomain, in my case.

**Comment by williamknauss** [comment]
Hi @Menti,
Yes sub directory installation has a few bugs that w are addressing. Take a look at #94 to follow the progress of getting this fixed.
