### ISSUE TITLE
Resolving Setup Issues

### ISSUE THREAD

**Issue by cdevroe** [plainmade/unmark#85]
Obviously, people are having issues setting up Unmark. There are always so many variables at play... the hosting environment, versions of PHP, Apache, mySQL, etc., the overall experience of the user, database permissions, file permissions, etc.

We honestly never expected to see so many issues with people setting up a simple Code Igniter application. But there are... many. Still opened at #56, #64, #68, #71, numbers #76, #77 in some ways, #79, #83 (upgrade issue, more or less), and #84.

Most of these are likely related. With some updates to our set up routine, error reporting, and installation instructions we can likely lick all of these in a single update. We want to let you all know, though, that we are going to address all of these issues in one update.

We'd love any help anyone would like to provide. That can be code, documentation, better error reporting in the application, anything you think might help people get Unmark set up for themselves.

One final note, on support... we've seen some claim they are going to get a hosted account and ask for support. We appreciate you trying to help us build Unmark with your hard earned money. But we don't offer Unmark open source to try to make any money. We offer it because far too often our favorite bookmarking services go away. The way we thought we'd be able to preserve Unmark for everyone would be to allow it to be open. So please, keep your money. Or donate it using the donate link. But don't buy a hosted subscription to try to get support for open setup issues here.

I'm about to take a small winter vacation. So, I'll likely not be addressing the setup issues until after that. But when I get back, I'll try to tackle them all at once. Stay tuned.

**Comment by cdevroe** [comment]
I'm back from vacation. :smile: :palm_tree: -> :frowning: :snowflake: 

So I'll start hopping onto some of these open issues soon. Thanks to @williamknauss for tackling a few while I was away. His PRs have been merged into master and are slated to be released in 1.6.2. There is only one issue left in 1.6.2 and, depending on how quickly some of the above referenced issues go, I may add a few more issues into this milestone.

If anyone would like to lend a hand we'd sincerely appreciate it. The easier Unmark is to install and upgrade the more people will be able to benefit from it.

**Comment by cdevroe** [comment]
A big thanks to @williamknauss for helping to get these issues cleared up. It looks like after today many of the setup issues that people were having with Unmark have been resolved in one way or another.

**Comment by williamknauss** [comment]
We honestly never expected to see so many issues with people setting up a simple Code Igniter application. But there are... many. Still opened at #56, ~~#64~~, ~~#68~~, #71, numbers ~~#76~~, ~~#77~~ in some ways, ~~#79~~, ~~#83~~ (upgrade issue, more or less), and ~~#84~~.
