### ISSUE TITLE
Bookmarklet doesn't work on Github.com

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#92]
I know technically this isn't an Unmark bug. It you try to run the Unmark+ Bookmarklet on any github.com page, it won't do anything. After reviewing Firebug console I found this:
![csp](https://cloud.githubusercontent.com/assets/2041571/6002791/72e49be4-aac4-11e4-9e93-d29ab2f3aac0.png)

Again I understand that this is not a Unmark+ problem, however I'm adding a bug report to see if we can maybe build a workaround for this problem?

**Comment by williamknauss** [comment]
After further review I found this to be a Firefox bug, the bookmarklet works on Github pages if I am in Chrome.

**Comment by williamknauss** [comment]
[More on this] (https://github.com/blog/1477-content-security-policy)

**Comment by cdevroe** [comment]
Yes, we've had this issue in the past with all browsers (see #49) but it appears the GitHub updated something. I suppose they simply didn't update Firefox for this.

I do not know what our options are here. I'd have to do some research.

**Comment by williamknauss** [comment]
Yes I agree this is a Firefox bug. I read somewhere but would have to find the link that we may be able to encapsulate the bookmarklet code in some CSS. However that sounds very "hackish" to me. Maybe we should just wait till Firefox fixes this bug.

**Comment by bryce-admin** [comment]
It still hasn't been fixed.  Moreover, it seems to not work on any site that uses SSL/TLS.  I've had to do the following in another browser tab to add those links:

http://links.example.com/mark/add?url=https://ssl.tls.whatever.example.com/foo.html

**Comment by nitinthewiz** [comment]
@bryce-admin that's a nice workaround!
