### ISSUE TITLE
Create Installer

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#93]
It would be great to see an installer created that would do the following:

- [ ] Check Installation Environment
  - [X] Verify PHP 5.4 or higher - williamknauss/unmark@6d9ce8fcaea91b9685a75465789a92e52e689d80
  - [X] Verify gettext is installed and enabled - williamknauss/unmark@d4ffdd006476e79a54be5a6396f63119fe667cf0
  - [ ] If webserver is Apache verify mod_rewrite is enabled
  - [X] Verify MYSql 5.5 or higher - williamknauss/unmark@efc0f0821a8e33bbe08a952d7cd69d14893a9a7b
- [X] Prompts
  - [X] Prompt developer to enter MYSql credentials
  - [X] Prompt the developer to save the database.php configuration
- [ ] Errors
  - [X] Display error for incorrect MYSql creds
  - [X] Display error for incorrect version of PHP
  - [X] Display error if gettext is not installed or enabled
  - [ ] Display error if webserver is Apache and mod rewrite is not enabled

**Comment by williamknauss** [comment]
The first problem I encountered:
I navigated to my new controller "installer" by going to http://subdomain.domain.tld/installer and got presented with "Eek, something is wrong" -
 "An unexpected error has occured
The issue has been logged and will be taken care of shortly."

This was caused by the database.php configuration file missing.  Looks like f13ea2efd264e0d8020f12105465fb0be5cdd9d8 needs expanded to include modifications to error_general.php.

**Comment by williamknauss** [comment]
###### Questions, Comments, Concerns, Dreams, or Aspirations
I want to make a note that this installer is not ready for production. It is merely a proposal. I made some core changes that need reviewed by @cdevroe. The two changes to keep in mind are:
1) I removed the database from autoload and loaded it up in the construct of the controllers
2) I choked the Unmark_localization hook if we are on the installer controller

Here is a list of things to polish this installer off before it hits the spotlight:
- [ ] UI Prettyfication
- [ ] Merging the installer, and install controllers together
- [ ] Testing:
  - [ ] OS
    - [ ] Windows
    - [ ] Linux
  - [ ] Web Servers
    - [ ] Apache
    - [ ] Nginx

**Comment by cdevroe** [comment]
I'm on the UI portions right now. *tag* :hand:

**Comment by williamknauss** [comment]
The initial install process looks good, I do have a concern with the textarea box. Would it be possible to left align the textarea box? As a side note making "Next Step" have the same blue button as "Install" on the previous step would be nice.
 
![installbox](https://cloud.githubusercontent.com/assets/2041571/6257570/3f17a6c6-b78f-11e4-9d1a-3d2e00396c32.png)

I'll look into trying to combining the controllers installer and install into one.

**Comment by williamknauss** [comment]
Made some major progress on this issue this weekend.

**Comment by Kickball** [comment]
This should check to see if mod_rewrite is enabled in apache2:

<code>if (in_array('mod_rewrite', apache_get_modules())) {
    code
}</code>

And this should be used for detecting the web server:

<code>$_SERVER["SERVER_SOFTWARE"]</code>

**Comment by cdevroe** [comment]
All: Would anyone like to pick up the ball here? Or is there any proposal to simply ditch it in favor of fixing the "set up" bugs that come along with CodeIgniter. I think upgrading the app to a current version of CodeIgniter will solve a lot of setup issues.

**Comment by cdevroe** [comment]
I think the current set of installation instructions are simple enough. Removing this.
