### ISSUE TITLE
Unmark Sub Directory Installation

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#94]
There are a few bugs when that I noticed when attempting to install Unmark in a subdirectory.

###### Server Environment:
* Windows 7 Professional
* Apache 2.4.9 (VC11)
* PHP 5.5.9

###### Steps to replicate problem:
* Create Apache VHost (books.10.0.4.93.xip.io)
* Clone Unmark into sub directory of VHost (git clone https://github.com/plainmade/unmark.git test)
* Navigate to Unmark setup (http://books.10.0.4.93.xip.io/test/setup) 

##### Problems
* The first problem encountered was when I navigated to (http://books.10.0.4.93.xip.io/test/setup) I was presented with a 404 error. From my years of working with CodeIgniter I know right away this is due to the htaccess file that is included with Unmark. [Reviewing this gives you an idea of the problem.] (http://stackoverflow.com/questions/15843692/codeigniter-installation-in-subdirectory)
![404](https://cloud.githubusercontent.com/assets/2041571/6090176/ad8044ce-ae3e-11e4-9738-e405ecf06833.png)

* Once I corrected my local .htaccess file I found not none of the styling or scripting was working. Reviewing the html source code revealed that all assets have been prefix with a "/", referring them to load from the root of the VHost. 
![nostyle](https://cloud.githubusercontent.com/assets/2041571/6090200/4b7212c0-ae3f-11e4-8d63-3bc1a62f5be9.png)

* Clicking on "INSTALL UNMARK" the browser sent me to http://books.10.0.4.93.xip.io/install which of course 404'd.
![install](https://cloud.githubusercontent.com/assets/2041571/6090215/0e985f02-ae40-11e4-9d1c-cb5554e0b16a.png)

Seeing as there are three separate problems here I will create three issues in Github, making this issue the "tracker" for visibility. Thanks to @yforster for pointing these issues out.

**Comment by williamknauss** [comment]
- [ ] .htaccess Update #95 
- [ ] Update Asset References #96
- [ ] Update hard coded links #97

**Comment by simonschaufi** [comment]
did you try to set the RewriteBase to /test/ in .htaccess?

**Comment by xrat** [comment]
So, installation in a sub directory is supposed to work now? Because it still says otherwise in `readme.md`.

**Comment by cdevroe** [comment]
@xrat Try #157 and see if it works. 

Otherwise, we'd love it if someone else tackled this as we're unsure if we'll support it out of the box. Would you mind making the needed updates and submitting a Pull Request?

**Comment by xrat** [comment]
Ah, I missed #157. Sorry, but I am not a programmer. Can't help much with the code.
I was following this as I wanted to install Unmark on a server with an existing SSL certificate. Since I have just switched to Let's Encrypt I might just as well create a new subdomain.
