### ISSUE TITLE
Unmark Sub Directory Installation .htaccess file

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#95]
When attempting to install Unmark in a sub directory of a domain the .htaccess file rewrites the URL's to the root of the subdomain essentially breaking Unmark.

**Comment by williamknauss** [comment]
While this PR fixes any Apache issues with installing in a sub directory I would really like to get input from an Nginx expert on the proper Nginx configuration. Can any experts confirm [nginx setup] (https://github.com/plainmade/unmark/wiki/Nginx-Configuration) will work for a sub directory?

**Comment by cdevroe** [comment]
@williamknauss I made a request on Twitter for some nginx people to take a look. If we don't get a response I'll personally reach out to a few people, Maybe even @kip9! https://twitter.com/cdevroe/status/565623629892042753
