### ISSUE TITLE
Unmark Sub Directory Installation assets

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#96]
When attempting to install Unmark in a subdirectory of a domain the assets are hard coded to "/{asset_path}". Assets should be loaded relative to the installation files of Unmark.

**Comment by cdevroe** [comment]
@williamknauss It looks like you've merged this into staging. Would you like me to test this prior to us merging it with master?

**Comment by williamknauss** [comment]
Hi @cdevroe,
I did merge this into staging but its not quite ready. This is a "3" part update. I using #94 as a tracking "issue" for all 3 steps. I need to finalize #97, then this is ready for full scale testing.

**Comment by cdevroe** [comment]
Going to close this off as it is pretty niche. If anyone runs across this issue in the future please create a new issue for it.
