### ISSUE TITLE
Unmark Sub Directory Installation Hard Coded Links

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#97]
When attempting to install Unmark in a subdirectory, some links are hard coded with a "/" in front of them. Links should be created relative to the installation files of Unmark

**Comment by williamknauss** [comment]
Leaving notes of the regex(s) used to locate hard coded links and such
Searching 28 files for "<a\s+(?:[^>]*?\s+)?href="([^"]*)"" (regex)

**Comment by williamknauss** [comment]
So I've run into a road block here. I'm way to spoiled by PHP's functionality here of: __DIR__, and CodeIgniter's FCPATH, APPPATH, and base_url();

Essentially Javascript doesn't have a way to give me a base url. I know all about $(location) but the closest thing to a CodeIgniter base_url() would be $(location).attr('origin); However origin doesn't include any sub directory paths that may be used.

Here are some potential ideas to make Javascript (JQuery) aware of the base url of the Unmark installation.

1) Define a pure Javascript variable in the head of all pages and use the url helper within CodeIgniter to set the base url.

2) Build a function in the Unmark.js file, something like baseurl and have it find all scripts in the dom, specifically looking for any file withing assets/js/production. Then find the fully qualified name (rather path or would it be considered URI?) of said script. Then remove the script name, and the path of assets/js/production and you would be left with the base url.

3) Hire the first random guy with a fancy bolwer, or wizard hat.

4) Define a meta in the header of each page something like <meta name="baseurl" content=<?php echo site_url(); ?>">, then use JQuery to extract said information.

While of course we know that number 3 won't work and number 2 is a bad idea (I mean messy idea). I personally lean towards number 4. 

Thoughts?

**Comment by cdevroe** [comment]
@williamknauss What about adding a configuration variable called $unmark_url? This can then be used for things like this.

**Comment by williamknauss** [comment]
@cdevroe 
Just checking for some clarification here, are you referring to making a meta tag called "unmark_url"?

**Comment by cdevroe** [comment]
@williamknauss No, a PHP variable in config. I think looking up a URL in jQuery -- either by reading the value of a header meta tag or by determining the URL using JavaScript is a heafty price on speed. I think if someone wants Unmark in a sub-directory they can type in a URL in config.php to allow for that.

What do you think?

**Comment by williamknauss** [comment]
CodeIgniter figures this out for us already, we just need to call:

```php
$this->config->base_url();
```

WOOT WOOT!

**Comment by tbleiker** [comment]
What's the status here? I try to install unmark in a sub directory. I think that I got the nginx config right. However, the browser downloads a file called "setup" with some php code inside whenever I call /unmark/setup :open_mouth:

**Comment by cdevroe** [comment]
@williamknauss Any direction for @tbleiker here?

**Comment by ghidra** [comment]
Wanted to chime in here, to see if there is any news on this.
I am running into the same issues that have been reported in the original ticket.

**Comment by cdevroe** [comment]
@tbleiker @ghidra Do you two still have this issue? And is it only on nginx? If your server is "downloading a PHP file" my guess is something is misconfigured other than the application.
